# Generated by Django 5.1.1 on 2024-10-26 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(
                default=datetime.date(2024, 10, 26), verbose_name="дата оплаты"
            ),
        ),
    ]
