# Generated by Django 5.1.1 on 2024-11-16 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="дата оплаты"
            ),
        ),
    ]
