# Generated by Django 5.1.1 on 2024-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="product",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
