# Generated by Django 5.1.1 on 2024-10-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="owner",
            new_name="user",
        ),
    ]
